'use client';

import {
  ThemeContextProvider,
  useThemeContext,
} from './context/ThemeContextProvider';
import './globals.css';

import { ThemeProvider, CssBaseline } from '@mui/material';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { theme } = useThemeContext();

  return (
    <html lang='en'>
      <head>
        <title>Create Next App</title>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <ThemeContextProvider>
        <ThemeProvider theme={theme}>
          <body id='__next'>
            {/* <CssBaseline /> */}
            {children}
          </body>
        </ThemeProvider>
      </ThemeContextProvider>
    </html>
  );
}
